server:
  port: 8100

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        vault:
          scheme: http
          host: 127.0.0.1
          port: 8200
          authentication: token
          token: root
          backend: dev
          kv-version: 2
          default-key: # disable default key - See org.springframework.cloud.config.server.environment.AbstractVaultEnvironmentRepository.defaultKey
    vault:
      enabled: false # Vault를 통해 현재 Application property를 읽는 설정 disabled

logging:
  level:
    org.springframework: trace